### PR TITLE
Rus text 2

### PR DESCRIPTION
**Pull request by SaloEater**
MCM and new lines

### CODE REVIEW

**Comment by SaloEater** [comment]
Honestly have no idea why there any hieroglyphs, lol

**Comment by bellyillish** [comment]
@SaloEater I think it's the encoding. I learned that the hard way when I was working on another mod.

The file should be encoded in Windows 1251. You probably already know that. But sometimes it'll default to another encoding in your editor without you noticing.

`/rus/idiots_mcm.xml` looks OK but I think `/rus/idiots.xml` is corrupted because of that (that's usually what those diamond-shaped question-mark characters mean).

Don't know what your editor of choice is, but I had to set this in my project to force the correct encoding all the time:
encoding

**Comment by bellyillish** [comment]
@SaloEater  Not sure what I did but somehow your `idiots_mcm.xml` Russian translation didn't make it into Beta 7. Sorry about that. I'm going to push another little update anyway, so I'll include it in there.

**Comment by bellyillish** [comment]
Added to Beta 8

**Pull request closed without merging**
